# client/Dockerfile.dev

# Use an official Node.js image as the base image
FROM node:20

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Set environment variable to enable polling for file changes (important for Docker)
ENV CHOKIDAR_USEPOLLING=true

# Expose the port the app runs on
EXPOSE 3000

# Start the React development server
CMD ["npm", "start"]