version: '3.8'

services:
  flask:
    build:
      context: ./server
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=73961200
      - DB_NAME=supermarkets_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 73961200
      MYSQL_DATABASE: supermarkets_db
    volumes:
      - db-data:/var/lib/mysql  # Persistent volume for MySQL data
      - ./server/supermarkets_db.sql:/docker-entrypoint-initdb.d/supermarkets_db.sql  # Correct SQL script mapping
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10

  react:
    build:
      context: ./client
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data: