name: Backend CI

on:
  push:
    paths:
      - 'server/**'
  pull_request:
    paths:
      - 'server/**'

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          MYSQL_USER: ${{ secrets.DB_APP_USER }}
          MYSQL_PASSWORD: ${{ secrets.DB_APP_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        # Ensure the init.sql is correctly mounted
        volumes:
          - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Adjust as needed

    - name: Install Dependencies
      run: |
        cd server
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate MySQL Initialization Script
      run: |
        echo "CREATE USER IF NOT EXISTS '${{ secrets.DB_APP_USER }}'@'%' IDENTIFIED BY '${{ secrets.DB_APP_PASSWORD }}';" > server/init.sql
        echo "GRANT ALL PRIVILEGES ON \`${{ secrets.DB_NAME }}\`.* TO '${{ secrets.DB_APP_USER }}'@'%';" >> server/init.sql
        echo "FLUSH PRIVILEGES;" >> server/init.sql

    - name: Wait for MySQL to be Ready
      timeout-minutes: 2
      run: |
        until mysqladmin ping -h "localhost" --silent; do
          echo "Waiting for MySQL..."
          sleep 5
        done

    - name: Verify MySQL Health
      if: failure()
      run: |
        echo "MySQL failed to start. Fetching logs..."
        docker logs ${{ job.services.mysql.id }}

    - name: Set Environment Variables
      run: |
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
        echo "DB_USER=${{ secrets.DB_APP_USER }}" >> $GITHUB_ENV
        echo "DB_PASSWORD=${{ secrets.DB_APP_PASSWORD }}" >> $GITHUB_ENV
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
        echo "FLASK_ENV=${{ secrets.FLASK_ENV }}" >> $GITHUB_ENV
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV

    - name: Apply Database Migrations
      run: |
        cd server
        source venv/bin/activate
        flask db upgrade  # Ensure Flask-Migrate is configured

    - name: Run Tests
      run: |
        cd server
        source venv/bin/activate
        python -m unittest discover -s tests

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: backend-test-results
        path: server/tests/results/  # Adjust the path as needed
